import Link from "next/link";

export default function TermsPage() {
  return (
    <main className="flex-1 flex flex-col">
      <nav className="px-8 py-6 border-b border-neutral-200">
        <Link href="/" className="font-serif-brand text-xl font-semibold">
          Parity
        </Link>
      </nav>
      <article className="prose prose-neutral max-w-3xl mx-auto px-6 py-12">
        <h1 className="font-serif-brand text-3xl font-semibold">Terms of use</h1>
        <p className="text-sm text-amber-800 bg-amber-50 border border-amber-200 rounded-lg p-3">
          Template only. Subject to review by a qualified Australian lawyer
          before public launch.
        </p>
        <h2>Not legal advice</h2>
        <p>
          Parity is an information tool. Every AI-generated answer, draft, and
          export is general information from your registered by-laws and
          Queensland legislation, not legal advice. You should seek independent
          legal advice for any binding decision.
        </p>
        <h2>Your data, your case</h2>
        <p>
          Evidence items you upload default to private. You alone decide what to
          share with your scheme. We do not share your data with the body
          corporate, the committee, or anyone else without your explicit opt-in
          per item.
        </p>
        <h2>Acceptable use</h2>
        <p>
          Parity is a neutral record-keeping tool. Do not use Parity to harass,
          defame, or intimidate others. Drafts generated by the system are
          non-inflammatory by default; if you override this and insert
          inflammatory content, you do so at your own legal risk.
        </p>
      </article>
    </main>
  );
}
